server:
 port: 8002
eureka:
 client:
  service-url:
   defaultZone: http://localhost:7001/eureka
 instance:
  #instance-id: microservicecloud-dept8002  #自定义服务名称信息
  #prefer-ip-address: true  #访问路径可以显示IP地址
spring:
 application:
  name: provider-dept